import type { INodeProperties } from 'n8n-workflow';

export const resourceProperty: INodeProperties = {
	displayName: 'Resource',
	name: 'resource',
	type: 'options',
	noDataExpression: true,
	options: [
		{ name: 'Attendance', value: 'attendance' },
		{ name: 'Document', value: 'document' },
		{ name: 'Email', value: 'email' },
		{ name: 'Request', value: 'request' },
		{ name: 'User', value: 'user' },
	],
	default: 'email',
};

export const operationProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['email'] } },
		options: [
			{
				name: 'Send',
				value: 'send',
				description: 'Send a custom email',
				action: 'Send an email',
			},
		],
		default: 'send',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['request'] } },
		options: [
			{
				name: 'Change Status',
				value: 'changeStatus',
				description: 'Change the status of a request (leave, permit, ...)',
				action: 'Change the status of a request',
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new request',
				action: 'Create a request',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get an existing request by ID',
				action: 'Get a request',
			},
			{
				name: 'Search',
				value: 'search',
				description: 'Search for existing requests by type, author, status and date range',
				action: 'Search requests',
			},
		],
		default: 'changeStatus',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['user'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new user',
				action: 'Create a user',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get an existing user by ID',
				action: 'Get a user',
			},
		],
		default: 'create',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['attendance'] } },
		options: [
			{
				name: 'Export Summary',
				value: 'exportSummary',
				description: "Export a period's attendance summary as an Excel file",
				action: 'Export the attendance summary',
			},
		],
		default: 'exportSummary',
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['document'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new document with an attachment',
				action: 'Create a document',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get an existing document by ID',
				action: 'Get a document',
			},
		],
		default: 'create',
	},
];

export const emailFields: INodeProperties[] = [
	{
		displayName: 'Recipient',
		name: 'recipient',
		type: 'string',
		placeholder: 'name@example.com',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['email'], operation: ['send'] } },
	},
	{
		displayName: 'Subject',
		name: 'subject',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['email'], operation: ['send'] } },
	},
	{
		displayName: 'Message',
		name: 'message',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		displayOptions: { show: { resource: ['email'], operation: ['send'] } },
	},
];

export const requestFields: INodeProperties[] = [
	{
		displayName: 'Request ID',
		name: 'requestId',
		type: 'number',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['request'], operation: ['changeStatus', 'get'] } },
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'Accepted', value: 'ACCETTATA' },
			{ name: 'Rejected', value: 'RIFIUTATA' },
			{ name: 'Awaiting Reviewer', value: 'IN_ATTESA_REVISORE' },
			{ name: 'Awaiting Reply', value: 'IN_ATTESA_RISPOSTA' },
		],
		default: 'ACCETTATA',
		required: true,
		displayOptions: { show: { resource: ['request'], operation: ['changeStatus'] } },
	},
	{
		displayName: 'Comment',
		name: 'comment',
		type: 'string',
		default: '',
		displayOptions: { show: { resource: ['request'], operation: ['changeStatus'] } },
	},
	{
		displayName: 'Request Type Name or ID',
		name: 'requestTypeId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getRequestTypes' },
		default: '',
		required: true,
		description:
			'Every request type has its own, per-tenant-configurable set of fields, loaded below once a type is chosen. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['request'], operation: ['create'] } },
	},
	{
		displayName: 'On Behalf of User Name or ID',
		name: 'requestOnBehalfOfUserId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getUsersForRequestCreate' },
		default: '',
		description:
			"If empty, the request is created for the service account's linked user. If set, requires the \"open on behalf of\" permission for the target user. Choose from the list, or specify an ID using an <a href=\"https://docs.n8n.io/code/expressions/\">expression</a>.",
		displayOptions: { show: { resource: ['request'], operation: ['create'] } },
	},
	{
		displayName: 'Initial Status',
		name: 'requestInitialStatus',
		type: 'options',
		options: [
			{ name: '(Default) Awaiting Reviewer', value: '' },
			{ name: 'Accepted', value: 'ACCETTATA' },
			{ name: 'Rejected', value: 'RIFIUTATA' },
			{ name: 'Awaiting Reply', value: 'IN_ATTESA_RISPOSTA' },
		],
		default: '',
		description:
			'Setting anything other than the default requires the "open on behalf of" permission',
		displayOptions: { show: { resource: ['request'], operation: ['create'] } },
	},
	{
		displayName: 'Request Fields',
		name: 'requestData',
		type: 'resourceMapper',
		default: { mappingMode: 'defineBelow', value: null },
		required: true,
		typeOptions: {
			loadOptionsDependsOn: ['requestTypeId'],
			resourceMapper: {
				resourceMapperMethod: 'getRequestFields',
				mode: 'add',
				fieldWords: { singular: 'field', plural: 'fields' },
				addAllFields: true,
			},
		},
		displayOptions: { show: { resource: ['request'], operation: ['create'] } },
	},
	{
		displayName: 'Request ID',
		name: 'searchRequestId',
		type: 'number',
		default: '',
		description: 'If set together with other filters, restricts the search to this specific request',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Request Type Name or ID',
		name: 'searchRequestTypeId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getRequestTypes' },
		default: '',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Author Name or ID',
		name: 'searchAuthorId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getUsersForRequestSearch' },
		default: '',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Status',
		name: 'searchStatus',
		type: 'options',
		options: [
			{ name: 'Accepted', value: 'ACCETTATA' },
			{ name: 'Any', value: '' },
			{ name: 'Awaiting Reply', value: 'IN_ATTESA_RISPOSTA' },
			{ name: 'Awaiting Reviewer', value: 'IN_ATTESA_REVISORE' },
			{ name: 'Rejected', value: 'RIFIUTATA' },
		],
		default: '',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Created After',
		name: 'searchStartDate',
		type: 'dateTime',
		default: '',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Created Before',
		name: 'searchEndDate',
		type: 'dateTime',
		default: '',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
	{
		displayName: 'Limit',
		name: 'searchLimit',
		type: 'number',
		default: 100,
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['request'], operation: ['search'] } },
	},
];

export const userFields: INodeProperties[] = [
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'number',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['get'] } },
	},
	{
		displayName: 'First Name',
		name: 'firstName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Last Name',
		name: 'lastName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'name@example.com',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Username',
		name: 'username',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Site Name or ID',
		name: 'siteId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getSitesForUser' },
		default: '',
		required: true,
		description: 'If the list is empty, the linked service account has no visibility over any site for user creation. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Company Name or ID',
		name: 'companyId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCompaniesForUser' },
		default: '',
		required: true,
		description: 'If the list is empty, the linked service account has no visibility over any company for user creation. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Role Names or IDs',
		name: 'roleIds',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getRoles' },
		default: [],
		required: true,
		description: 'At least one role is required. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['user'], operation: ['create'] } },
		options: [
			{
				displayName: 'Address of Residence',
				name: 'residenceAddress',
				type: 'string',
				default: '',
			},
			{ displayName: 'City of Residence', name: 'residenceCity', type: 'string', default: '' },
			{ displayName: 'Date of Birth', name: 'dateOfBirth', type: 'dateTime', default: '' },
			{ displayName: 'Employee ID', name: 'employeeId', type: 'string', default: '' },
			{ displayName: 'Fiscal Code', name: 'fiscalCode', type: 'string', default: '' },
			{ displayName: 'IBAN', name: 'iban', type: 'string', default: '' },
			{
				displayName: 'Language',
				name: 'language',
				type: 'options',
				options: [
					{ name: 'Italian', value: 'it' },
					{ name: 'English', value: 'en' },
					{ name: 'Spanish', value: 'es' },
					{ name: 'Portuguese', value: 'pt' },
				],
				default: 'it',
			},
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'Europe/Rome' },
		],
	},
];

export const attendanceFields: INodeProperties[] = [
	{
		displayName: 'Format',
		name: 'format',
		type: 'options',
		options: [
			{ name: 'Multi-Sheet (One Sheet per User)', value: 'corem-multi-foglio' },
			{ name: 'Single Sheet (All Users)', value: 'corem-singolo-foglio' },
		],
		default: 'corem-multi-foglio',
		required: true,
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'Start Date',
		name: 'startDate',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'End Date',
		name: 'endDate',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'Site Name or ID',
		name: 'siteId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getSitesForAttendance' },
		default: '',
		description: 'If set together with Team or Company, it takes precedence over both. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'Team Name or ID',
		name: 'teamId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTeamsForAttendance' },
		default: '',
		description: 'Only considered if Site is not set. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'Company Name or ID',
		name: 'companyId',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getCompaniesForAttendance' },
		default: '',
		description: 'Only considered if Site and Team are not set. If none of the three fields is set, the export includes all visible users. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
	{
		displayName: 'Put Output File in Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		description: 'Name of the binary property to which the exported Excel file will be written',
		displayOptions: { show: { resource: ['attendance'], operation: ['exportSummary'] } },
	},
];

export const documentFields: INodeProperties[] = [
	{
		displayName: 'Document ID',
		name: 'documentId',
		type: 'number',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['document'], operation: ['get'] } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['document'], operation: ['create'] } },
	},
	{
		displayName: 'Input Binary Field',
		name: 'inputBinaryField',
		type: 'string',
		default: 'data',
		required: true,
		description: 'Name of the input binary property containing the attachment to upload',
		displayOptions: { show: { resource: ['document'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['document'], operation: ['create'] } },
		options: [
			{ displayName: 'Description', name: 'description', type: 'string', default: '' },
			{
				displayName: 'Read Only',
				name: 'readOnly',
				type: 'boolean',
				default: false,
				description: 'Whether the document can only be viewed, not edited, by those it is shared with',
			},
			{
				displayName: 'Site Names or IDs',
				name: 'siteIds',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getSitesForDocument' },
				default: [],
				description:
					'Sites to share the document with. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'Team Names or IDs',
				name: 'teamIds',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getTeamsForDocument' },
				default: [],
				description:
					'Teams to share the document with. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
			{
				displayName: 'User Names or IDs',
				name: 'userIds',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getUsersForDocument' },
				default: [],
				description:
					'Users to share the document with. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
			},
		],
	},
];
